[pytest]
markers =
    projection
    delete_comments
    user_report
    create_update_comments
    timeouts
    errors
    error_handling
    facets
    paging
    migration
    user_management
    faceted_search
    connection
    usefixtures('config')
    connection
    text_and_subfield_search
    get_comments
    user_preferences
    connection_pooling
